# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ v4-dev ]
  pull_request:
    branches: [ v4-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install
      - name: Check with lint
        run: yarn lint    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/
      - name: Upload to Server
        uses: up9cloud/action-rsync@master
        env:
          USER: ${{secrets.DEPLOY_SSH_USER}}
          HOST: ${{secrets.DEPLOY_SSH_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          ARGS: -rzh -O --delete-before
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: dist/
          TARGET: ${{secrets.DEPLOY_SSH_V4_DEV_TARGET}}
